# Generated by Django 5.0 on 2025-12-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(blank=True, choices=[('official', 'Official'), ('community', 'Community')], max_length=250),
        ),
    ]
