# Generated by Django 5.0 on 2025-12-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='event_type_icon',
            field=models.ImageField(blank=True, null=True, upload_to='event_type_icons/'),
        ),
    ]
